const songList = [
    // {
      //   artist: 'Chuck Berry',
      //   song: 'Johnny B Goode', 
      //   lyrics: 
      //   `Deep down in Louisiana, close to New Orleans,
      //   Way back up in the woods among the evergreens,
      //   There stood a log cabin made of earth and wood,
      //   Where lived a country boy named Johnny B. Goode,
      //   Who never ever learned to read or write so well,
      //   But he could play the guitar just a-ringin' a bell,`
      // },
      // {
      //   artist: 'Spice Girls',
      //   song: 'Wannabe',
      //   lyrics: `Yo I'll tell you what I want,
      //           what I really really want,
      //           So tell me what you want,
      //           what you really really want,
      //           I'll tell you what I want, 
      //           what I really really want,`
      // },
      // {
      //   artist: 'Queen',
      //   song: 'We Will Rock You',
      //   lyrics: `Buddy you're a boy make a big noise,
      //   Playing in the street,
      //   gonna be a big man someday,
      //   You got mud on your face,
      //   you big disgrace,
      //   Kicking your can all over the place singin',`
      // },
      // {
      //   artist: 'Taylor Swift',
      //   song: 'Shake it off',
      //   lyrics: `I stay out too late,
      //   Got nothing in my brain,
      //   That's what people say mm-mm,
      //   That's what people say mm-mm,
      //   I go on too many dates,
      //   But I can't make 'em stay,`
      // },
      // {
      //   artist: 'Carly Rae Jepsen',
      //   song: 'Call Me Maybe',
      //   lyrics: `I threw a wish in the well,
      //   Don't ask me I'll never tell,
      //   I looked to you as it fell,
      //   And now you're in my way,
      //   I trade my soul for a wish,
      //   Pennies and dimes for a kiss,`
      // },
      // {
      //   artist: 'Vanilla Ice',
      //   song: `Rollin' in my 5.0`,
      //   lyrics: `Turn up the volume,
      //           crank up the bass,
      //           Aww yeah Vanilla Ice is in the place,
      //           I'm here to tell ya a little story 'bout my 5.0,
      //           Just a-lettin' ya know I'm in total control,
      //           Oh yes many people know that I got good taste,`
      // },
      // {
      //   artist: 'Backstreet Boys',
      //   song: 'I Want it That Way',
      //   lyrics: `Yeah-eh-heah,
      //           You are my fire,
      //           The one desire,
      //           Believe when I say,
      //           I want it that way,
      //           But we are two worlds apart,`
      // },
      // {
      //   artist: 'Scissor Sisters',
      //   song: 'Take Your Mama',
      //   lyrics: `When you grow up,
      //            livin' like a good boy oughta,
      //           And your mama takes a shine to her best son,
      //           Something different,
      //           all the girls they seem to like you,
      //           Cause you're handsome,`
      // },
      // {
      //   artist: 'Johnny Cash',
      //   song: 'Ring of Fire',
      //   lyrics: `Love is a burnin' thing,
      //             And it makes a fiery ring,
      //             Bound by wild desire,
      //             I fell into a ring of fire,
      //             I fell into a burnin' ring of fire,
      //             I went down down down,`
      // },
      // {
      //   artist: 'David Bowie',
      //   song: 'Rebel Rebel',
      //   lyrics: `Doo doo doo-doo doo doo doo doo,
      //             Doo doo doo-doo doo doo doo doo,
      //             Doo doo doo-doo doo doo doo doo,
      //             You've got your mother in a whirl,
      //             She's not sure if you're a boy or a girl,
      //             Hey babe your hair's alright,`
      // },
      // {
      //   artist: 'Twister Sister',
      //   song: `We're Not Gonna Take It`,
      //   lyrics: `Oh we're not gonna take it,
      //             No, we ain't gonna take it,
      //             Oh we're not gonna take it anymore,
      //             We've got the right to choose it,
      //             There ain't no way we'll lost it,
      //             This is our life this is our song,`
      // },
      // {
      //   artist: 'Olivia Rodrigo',
      //   song: 'Drivers Licence',
      //   lyrics: `I got my driver's license last week,
      //             Just like we always talked about,
      //             'Cause you were so excited for me,
      //             To finally drive up to your house,
      //             But today I drove through the suburbs,
      //             Crying 'cause you weren't around,
      //   `
      // },
      // {
      //   artist: 'The Doors',
      //   song: 'Light My Fire',
      //   lyrics: `You know that it would be untrue,
      //             You know that I would be a liar,
      //             If I was to say to you,
      //             Girl we couldn't get much higher,
      //             Come on baby, light my fire,
      //             Come on baby, light my fire,`
      // },
      // {
      //   artist: 'Eminem ft Beyonce',
      //   song: 'Walk on Water',
      //   lyrics: `I walk on water,
      //             But I ain't no Jesus,
      //             I walk on water,
      //             But only when it freezes,
      //             Why are expectations so high?,
      //             Is it the bar I set?,`
      // },
      // {
      //   artist: 'Lewis Capaldi',
      //   song: 'Someone you Loved',
      //   lyrics: `I'm going under and this time I fear there's no one to save me,
      //             This all or nothing really got a way of driving me crazy,
      //             I need somebody to heal,
      //             Somebody to know,
      //             Somebody to have,
      //             Somebody to hold,`
      // },
      // {
      //   artist: 'The Libertines',
      //   song: `Can't Stand me now`,
      //   lyrics: `An ending fitting for the start,
      //             You twist and tore our love apart, 
      //             Your light fingers threw the dark,
      //             That shattered the lamp and into darkness it cast us,  
      //             No you've got it the wrong way round,
      //             You shut me up and blamed it on the brown,`
      // },
      // {
      //   artist: 'Arctic Monkeys',
      //   song: 'Do I Wanna Know?',
      //   lyrics: `Have you got color in your cheeks,
      //             Do you ever get the feeling that you can't shift the tide,
      //             That sticks around like something's in your teeth,
      //             And some aces up your sleeve,
      //             I had no idea that you're in deep,
      //             I dreamt about you near me every night this week,`
      // },
      // {
      //   artist: 'Bonnie Tyler',
      //   song: 'Holding Out for a Hero',
      //   lyrics: `Where have all the good men gone,
      //             And where are all the gods?,
      //             Where's the streetwise Hercules to fight the rising odds?,
      //             Isn't there a white knight upon a fiery steed?,
      //             Late at night I toss and I turn,
      //             And I dream of what I need,`
      // },
      // {
      //   artist: 'Tina Turner',
      //   song: `We Don't Need Another Hero`,
      //   lyrics: `Out of the ruins,
      //             Out from the wreckage, 
      //             Can't make the same mistake this time, 
      //             We are the children,
      //             The last generation, 
      //             We are the ones they left behind,`
      // },
      // {
      //   artist: 'Elton John',
      //   song: `Rocket Man`,
      //   lyrics: `She packed my bags last night pre-flight,
      //             Zero hour nine AM,
      //             And I'm gonna be high as a kite by then,
      //             I miss the earth so much I miss my wife,
      //             It's lonely out in space,
      //             On such a timeless flight,`
      // },
      // {
      //   artist: 'Billy Joel',
      //   song: `Always a Woman`,
      //   lyrics: `She can kill with a smile,
      //             she can wound with her eyes,
      //             She can ruin your faith with her casual lies,
      //             And she only reveals what she wants you to see,
      //             She hides like a child,
      //             but she's always a woman to me,`
      // },
      // {
      //   artist: 'Prince',
      //   song: `Little Red Corvette`,
      //   lyrics: `I guess I should of known,
      //             By the way you parked your car sideways,
      //             That it wouldn't last,
      //             See you're the kinda person,
      //             That believes in makin' out once,
      //             Love 'em and leave 'em fast,`
      // },
      // {
      //   artist: 'The Monkees',
      //   song: `Daydream Believer`,
      //   lyrics: `Oh I could hide 'neath the wings,
      //             Of the bluebird as she sings,
      //             The six-o'clock alarm would never ring,
      //             But six rings and I rise,
      //             Wipe the sleep out of my eyes,
      //             The shaving razor's cold and it stings,`
      // },
      // {
      //   artist: 'The Streets',
      //   song: `Dry Your Eyes`,
      //   lyrics: `And I'm just standin' there,
      //               I can't say a word,
      //               'Cause everything's just gone,
      //               I've got nothin' absolutely nothin',
      //               In one single moment your whole life can turn 'round,
      //               I stand there for a minute starin' straight into the ground,`
      // },
      // {
      //   artist: 'Kate Bush',
      //   song: `Wuthering Heights`,
      //   lyrics: `Out on the wiley windy moors,
      //             We'd roll and fall in green,
      //             You had a temper like my jealousy,
      //             Too hot too greedy,
      //             How could you leave me,
      //             When I needed to possess you?,`
      // },
      // {
      //   artist: 'Muse',
      //   song: `Supermassive Black Hole`,
      //   lyrics: `Oh baby don't you know I suffer?,
      //             Oh baby can you hear me moan?,
      //             You caught me under false pretenses,
      //             How long before you let me go?,
      //             Ooh you set my soul alight,
      //             Ooh you set my soul alight,`
      // },
      // {
      //   artist: 'Mark Morrison',
      //   song: `Return of the Mack`,
      //   lyrics: `Oooooh…,
      //             Come on,
      //             Ooh yeah,
      //             Well I tried to tell you so,
      //             (Yes I did),
      //             But I guess you didn't know,`
      // },
      // {
      //   artist: 'Sia',
      //   song: `Chandelier`,
      //   lyrics: `Party girls don't get hurt,
      //             Can't feel anything,
      //             when will I learn,
      //             I push it down,
      //             push it down,
      //             I'm the one "for a good time call"`
      // },
      // {
      //   artist: 'Black Sabbath',
      //   song: `War Pigs`,
      //   lyrics: `Generals gathered in their masses,
      //             Just like witches at black masses,
      //             Evil minds that plot destruction,
      //             Sorcerer of death's construction,
      //             In the fields the bodies burning,
      //             As the war machine keeps turning,`
      // },
      // {
      //   artist: 'Rage Against The Machine',
      //   song: `Sleep Now in the Fire`,
      //   lyrics: `The world is my expense,
      //             The cost of my desire,
      //             Jesus blessed me with its future,
      //             And I protect it with fire,
      //             So raise your fists,
      //             And march around,`
      // },
      // {
      //   artist: 'Ariana Grande',
      //   song: `7 Rings`,
      //   lyrics: `Yeah breakfast at Tiffany's and bottles of bubbles,
      //             Girls with tattoos who like getting in trouble,
      //             Lashes and diamonds ATM machines,
      //             Buy myself all of my favorite things (Yeah),
      //             Been through some bad shit I should be a sad bitch,
      //             Who woulda thought it'd turn me to a savage?,`
      // },
      // {
      //   artist: 'Joe Walsh',
      //   song: `Rocky Mountain Way`,
      //   lyrics: `Spent the last year,
      //             Rocky Mountain Way,
      //             Couldn't get much higher,
      //             Out to pasture,
      //             Think it's safe to say,
      //             Time to open fire,`
      // },
      // {
      //   artist: 'Rainbow',
      //   song: `Since You've Been Gone`,
      //   lyrics: `I get the same old dream,
      //               same time every night,
      //               Fall to the ground and I wake up,
      //               So I get out of bed put on my shoes and in my head,
      //               Thoughts fly back to the break-up,
      //               These four walls are closing in,`
      // },
      // {
      //   artist: 'Alice Cooper',
      //   song: `Poison`,
      //   lyrics: `Your cruel device,
      //               Your blood like ice,
      //               One look could kill,
      //               My pain your thrill,
      //               I wanna love you but I better not touch (don't touch),
      //               I wanna hold you but my senses tell me to stop,`
      // },
      // {
      //   artist: 'ABBA',
      //   song: `S.O.S`,
      //   lyrics: `Where are those happy days,
      //             they seem so hard to find,
      //             I tried to reach for you,
      //             but you have closed your mind,
      //             Whatever happened to our love?,
      //             I wish I understood,`
      // },
      // {
      //   artist: 'Michael Jackson',
      //   song: `Billie Jean`,
      //   lyrics: `She was more like a beauty queen from a movie scene,
      //             I said don't mind but what do you mean I am the one,
      //             Who will dance on the floor in the round,
      //             She said I am the one who will dance on the floor in the round,
      //             She told me her name was Billie Jean as she caused a scene,
      //             Then every head turned with eyes that dreamed of being the one,`
      // },
      // {
      //   artist: 'Aretha Franklin',
      //   song: `Respect`,
      //   lyrics: `What you want,
      //             Baby I got it,
      //             What you need,
      //             Do you know I got it,
      //             All I'm askin',
      //             Is for a little respect when you get home (just a little bit),`
      // },
      // {
      //   artist: 'Dusty Springfield',
      //   song: `Son of a Preacher Man`,
      //   lyrics: `Today I went out on a movie call,
      //             I saw a million nervous faces,
      //             I knew them all,
      //             Hollywood movie girls,
      //             We're all wearing our one good interview dress,
      //             The one showin' our legs,`
      // },
      // {
      //   artist: 'Tina Turner',
      //   song: `The Best`,
      //   lyrics: `I call you when I need you my heart's on fire,
      //             You come to me come to me wild and wired,
      //             Oh you come to me give me everything I need,
      //             Give me a life time of promises and a world of dreams,
      //             Speak the language of love like you know what it means,
      //             Mm and it can't be wrong take my heart and make it strong babe,`,
      // },
      // {
      //   artist: 'Gloria Gaynor',
      //   song: `I Will Survive`,
      //   lyrics: `At first I was afraid I was petrified,
      //             Kept thinking I could never live without you by my side,
      //             But then I spent so many nights thinking how you did me wrong,
      //             And I grew strong,
      //             And I learned how to get along,
      //             And so you're back,`,
      // },
      // {
      //   artist: 'Survivor',
      //   song: `Eye of the Tiger`,
      //   lyrics: `Rising up back on the street,
      //             Did my time took my chances,
      //             Went the distance now I'm back on my feet,
      //             Just a man and his will to survive,
      //             So many times it happens too fast,
      //             You trade your passion for glory,`,
      // },
      // {
      //   artist: 'Vanessa Carlton',
      //   song: `A Thousand Miles`,
      //   lyrics: `Making my way downtown walking fast,
      //             Faces pass and I'm home bound,
      //             Staring blankly ahead just making my way,
      //             Making a way through the crowd,
      //             And I need you,
      //             And I miss you,`,
      // },
      // {
      //   artist: 'The Who',
      //   song: `Behind Blue Eyes`,
      //   lyrics: `No one knows what it's like,
      //             To be the bad man,
      //             To be the sad man,
      //             Behind blue eyes,
      //             No one knows what it's like,
      //             To be hated,`,
      // },
      // {
      //   artist: 'The Animals',
      //   song: `The House of the Rising Sun`,
      //   lyrics: `There is a house in New Orleans,
      //             They call the Rising Sun,
      //             And it's been the ruin of many a poor boy,
      //             And God I know I'm one,
      //             My mother was a tailor,
      //             She sewed my new blue jeans,`,
      // },
      // {
      //   artist: 'MeatLoaf',
      //   song: `Bat out of Hell`,
      //   lyrics: `The sirens are screaming and the fires are howling,
      //             Way down in the valley tonight,
      //             There's a man in the shadows with a gun in his eye,
      //             And a blade shining oh so bright,
      //             There's evil in the air and there's thunder in sky,
      //             And a killer's on the bloodshot streets,`,
      // },
      // {
      //   artist: 'The Rolling Stones',
      //   song: `Start Me Up`,
      //   lyrics: `If you start me up,
      //             If you start me up I'll never stop,
      //             You can start me up,
      //             You can start me up I'll never stop,
      //             I've been running hot,
      //             You got me ticking going to blow my top,`,
      // },
      // {
      //   artist: 'The Rolling Stones',
      //   song: `Paint it Black`,
      //   lyrics: `I see a red door and I want it painted black,
      //             No colors anymore I want them to turn black,
      //             I see the girls walk by dressed in their summer clothes,
      //             I have to turn my head until my darkness goes,
      //             I see a line of cars and they're all painted black,
      //             With flowers and my love both never to come back,`,
      // },
      // {
      //   artist: 'Solomon Burke',
      //   song: `Cry to Me`,
      //   lyrics: `When your baby leaves you all alone,
      //   And nobody call you on the phone,
      //   Doncha feel like crying,
      //   Doncha feel like crying ,
      //   Well here I am my honey,
      //   c'mon baby cry to me,`,
      // },
      // {
      //   artist: 'Sam Cooke',
      //   song: `Wonderful World`,
      //   lyrics: `Don't know much about history,
      //             Don't know much biology,
      //             Don't know much about a science book,
      //             Don't know much about the french I took,
      //             But I do know that I love you,
      //             And I know that if you love me too,`,
      // },
      // {
      //   artist: 'Dion',
      //   song: `Runaround Sue`,
      //   lyrics: `Here's my story it's sad but true,
      //             It's about a girl that I once knew,
      //             She took my love then ran around,
      //             With every single guy in town,
      //             Yeah I should have known it from the very start,
      //             This girl will leave me with a broken heart,`,
      // },
      // {
      //   artist: 'Fats Domino',
      //   song: `Sick and Tired`,
      //   lyrics: `Oh baby whatcha gonna do,
      //             Oh baby whatcha gonna do,
      //             I'm sick and tired of foolin' around with you,
      //             Wake up in the mornin' fix you somethin' to eat,
      //             'fore I go to work I even brush your teeth,
      //             Get home in the evenin' and you're still in bed,`,
      // },
      // {
      //   artist: 'Dean Martin',
      //   song: `That's Amore`,
      //   lyrics: `When a moon hits your eye like a big pizza pie,
      //             That's amore,
      //             When the world seems to shine like you've had too much wine,
      //             That's amore,
      //             Bells will ring ting-a-ling-a-ling, ting-a-ling-a-ling,
      //             And you'll sing Vita bella,`,
      // },
      // {
      //   artist: 'Buddy Holly & The Crickets',
      //   song: `Peggy Sue`,
      //   lyrics: `If you knew Peggy Sue,
      //             Then you'd know why I feel blue without Peggy,
      //             My Peggy Sue,
      //             Oh well I love you gal, 
      //             yes I love you Peggy Sue,
      //             Peggy Sue Peggy Sue,`,
      // },
      // {
      //   artist: 'Little Richard',
      //   song: `Long Tall Sally`,
      //   lyrics: `Gonna tell Aunt Mary 'bout Uncle John,
      //             He claim he has the misery but he's havin' a lot of fun,
      //             Oh baby yeah baby woo,
      //             Havin' me some fun tonight yeah,
      //             Well long tall Sally,
      //             She's built for speed she got`,
      // },
      // {
      //   artist: 'Johnny Cash',
      //   song: `Man in Black`,
      //   lyrics: `Well you wonder why I always dress in black,
      //             Why you never see bright colors on my back,
      //             And why does my appearance seem to have a somber tone,
      //             Well there's a reason for the things that I have on,
      //             I wear the black for the poor and the beaten down,
      //             Livin' in the hopeless hungry side of town,`,
      // },
      // {
      //   artist: 'Johnny Cash',
      //   song: `A Boy Named Sue`,
      //   lyrics: `Well my daddy left home when I was three,
      //             Didn't leave very much to my mom and me,
      //             Except this old guitar and an empty bottle of booze,
      //             Now I don't blame him 'cause he run and hid,
      //             But the meanest thing that my daddy ever did,
      //             Was before he left he went and named me Sue,`,
      // },
      // {
      //   artist: 'Franki Lymon & the Teenagers',
      //   song: `Why do Fools Fall in Love`,
      //   lyrics: `Oh wah oh wah oh wah oh wah oh wah oh wah,
      //             Why do fools fall in love?,
      //             Why do birds sing so gay?,
      //             And lovers await the break of day,
      //             Why do they fall in love?,
      //             Why does the rain fall from above?,`,
      // },
      // {
      //   artist: 'The Mamas & The Papas',
      //   song: `California Dreamin`,
      //   lyrics: `All the leaves are brown (all the leaves are brown),
      //             And the sky is grey (and the sky is grey),
      //             I've been for a walk (I've been for a walk),
      //             On a winter's day (on a winter's day),
      //             I'd be safe and warm (I'd be safe and warm),
      //             If I was in L.A. (if I was in L.A.),`,
      // },
      // {
      //   artist: 'Eagles',
      //   song: `Hotel California`,
      //   lyrics: `On a dark desert highway,
      //             cool wind in my hair,
      //             Warm smell of colitas, 
      //             rising up through the air,
      //             Up ahead in the distance, 
      //             I saw a shimmering light,`,
      // },
      // {
      //   artist: 'Led Zeppelin',
      //   song: `Stairway to Heaven`,
      //   lyrics: `There's a lady who's sure,
      //   All that glitters is gold,
      //   And she's buying a stairway to heaven,
      //   When she gets there she knows,
      //   If the stores are all closed,
      //   With a word she can get what she came for,`,
      // },
      // {
      //   artist: 'Led Zeppelin',
      //   song: `Dazed and Confused`,
      //   lyrics: `Been dazed and confused for so long it's not true,
      //             Wanted a woman never bargained for you,
      //             Lots of people talk and few of them know,
      //             Soul of a woman was created below yeah,
      //             You hurt and abused tellin' all of your lies,
      //             Run around sweet baby, Lord how they hypnotize,`,
      // },
      // {
      //   artist: 'Rick Astley',
      //   song: `Never Gonna Give You Up`,
      //   lyrics: `We're no strangers to love,
      //             You know the rules and so do I,
      //             A full commitment's what I'm thinking of,
      //             You wouldn't get this from any other guy,
      //             I just want to tell you how I'm feeling,
      //             Gotta make you understand,`,
      // },
      // {
      //   artist: 'Leo Sayer',
      //   song: `Thunder In My Heart`,
      //   lyrics: `Standing here alone with you,
      //   Wondering what it is that I'm supposed to do,
      //   And there you are with the love light in your eyes,
      //   The bridges are burnt down,
      //   your arms are open wide,
      //   Am I in too deep or should I swim to the shore?,`,
      // },
      // {
      //   artist: 'Leo Sayer',
      //   song: `Moonlighting`,
      //   lyrics: `He sees her at the same time every night,
      //   At the Mexican discotheque,
      //   She gives him French kisses,
      //   He gives her French cigarettes,
      //   They sit at the same table every time,
      //   The lights are low but their eyes shine,`,
      // },
      // {
      //   artist: 'Meatloaf & Ellen Foley',
      //   song: `Paradise by the Dashboard Light`,
      //   lyrics: `Well I remember every little thing,
      //   As if it happened only yesterday,
      //   Parking by the lake,
      //   And there was not another car in sight,
      //   And I never had a girl,
      //   Looking any better than you did,`,
      // },
      // {
      //   artist: 'Billie Eilish',
      //   song: `You Should See Me in a Crown`,
      //   lyrics: `Bite my tongue bide my time,
      //             Wearing a warning sign,
      //             Wait 'til the world is mine,
      //             Visions I vandalize,
      //             Cold in my kingdom size,
      //             Fell for these ocean eyes,`,
      // },
      // {
      //   artist: 'Rupert Holmes',
      //   song: `Escape`,
      //   lyrics: `I was tired of my lady,
      //   We'd been together too long,
      //   Like a worn out recording,
      //   Of a favorite song,
      //   So while she lay there sleeping,
      //   I read the paper in bed,`,
      // },
      // {
      //   artist: 'Alanis Morrissette',
      //   song: `Ironic`,
      //   lyrics: `An old man turned ninety-eight,
      //             He won the lottery and died the next day,
      //             It's a black fly in your Chardonnay,
      //             It's a death row pardon two minutes too late,
      //             Isn't it ironic don't you think,
      //             It's like rain on your wedding day,`,
      // },
      // {
      //   artist: 'The Beach Boys',
      //   song: `Good Vibrations`,
      //   lyrics: `I love the colorful clothes she wears,
      //             And the way the sunlight plays upon her hair,
      //             I hear the sound of a gentle word,
      //             On the wind that lifts her perfume through the air,
      //             I'm pickin' up good vibrations,
      //             She's giving me excitations,`,
      // },
      // {
      //   artist: 'The Prodigy',
      //   song: `Firestarter`,
      //   lyrics: `I'm the trouble starter,
      //             punkin' instigator,
      //             I'm the fear addicted,
      //             danger illustrated,
      //             I'm a firestarter,
      //             twisted firestarter,`,
      // },
      // {
      //   artist: 'The Kinks',
      //   song: `You Really Got Me`,
      //   lyrics: `Girl you really got me goin',
      //   You got me so I don't know what I'm doin' now,
      //   Yeah, you really got me now,
      //   You got me so I can't sleep at night,
      //   Yeah, you really got me now,
      //   You got me so I don't know what I'm doin' now,`,
      // },
      // {
      //   artist: 'Aerosmith',
      //   song: `Dream On`,
      //   lyrics: `Every time when I look in the mirror,
      //             All these lines on my face getting clearer,
      //             The past is gone,
      //             It went by, like dusk to dawn,
      //             Isn't that the way,
      //             Everybody's got the dues in life to pay,`,
      // },
      // {
      //   artist: 'Bon Jovi',
      //   song: `Livin on a Prayer`,
      //   lyrics: `Tommy used to work on the docks, 
      //             union's been on strike,
      //             He's down on his luck, 
      //             it's tough so tough,
      //             Gina works the diner all day working for her man
      //             She brings home her pay for love for love`,
      // },
      // {
      //   artist: 'Madonna',
      //   song: `Like a Prayer`,
      //   lyrics: `Life is a mystery everyone must stand alone,
      //             I hear you call my name,
      //             And it feels like home,
      //             When you call my name it's like a little prayer,
      //             I'm down on my knees I wanna take you there,
      //             In the midnight hour I can feel your power,`,
      // },
      // {
      //   artist: 'The Beatles',
      //   song: `I Want to Hold Your Hand`,
      //   lyrics: `Oh yeah I tell you somethin',
      //               I think you'll understand,
      //               When I say that somethin',
      //               I want to hold your hand,
      //               I want to hold your hand,
      //               I want to hold your hand,`,
      // },
      // {
      //   artist: 'Simon & Garfunkel',
      //   song: `The Sound of Silence`,
      //   lyrics: `Hello darkness my old friend,
      //             I've come to talk with you again,
      //             Because a vision softly creeping,
      //             Left its seeds while I was sleeping,
      //             And the vision that was planted in my brain,
      //             Still remains,`,
      // },
      // {
      //   artist: 'Simon & Garfunkel',
      //   song: `Bridge Over Troubled Water`,
      //   lyrics: `When you're weary feeling small,
      //               When tears are in your eyes,
      //               I will dry them all,
      //               I'm on your side,
      //               Oh when times get rough,
      //               And friends just can't be found,`,
      // },
      // {
      //   artist: 'Pulp',
      //   song: `Common People`,
      //   lyrics: `She came from Greece she had a thirst for knowledge,
      //               She studied sculpture at Saint Martin's College,
      //               That's where I,
      //               Caught her eye,
      //               She told me that her Dad was loaded,
      //               I said In that case I'll have a rum and coca-cola,`,
      // },
    ]

    export default songList